import os
from building import *

cwd = GetCurrentDir()

# drivers already moved to the device model (platform drivers bound by the device tree).
# The rest of the old sources is not built until it is rewritten (see the porting list).
drivers = [
    ('timer/riscv_machine_timer.c', ''),
    ('clock_control/ccu-sun252i.c', ''),
    ('interrupt_controller/pic-plic.c', ''),
    ('pinctrl/pinctrl-sun252i.c', ''),
    ('pinctrl/jtag-sun252i.c', ''),
    ('dma/dma-sun252i.c', ''),
    ('watchdog/watchdog-sun252i.c', 'RT_USING_WDT'),
    ('i2c/i2c-sun252i.c', ''),
    ('spi/spi-sun252i.c', 'RT_USING_SPI'),
    ('spif/spif-sun252i.c', 'RT_USING_MTD_NOR'),
    ('pwm/pwm-sun252i.c', ''),
    ('pwm/pwm-bl-sun252i.c', ''),
    ('adc/adc-sun252i.c', 'RT_USING_ADC'),
    ('sdio/sdio-sun252i.c', 'RT_USING_SDIO'),
    ('mbus/mbus-sun252i.c', 'BSP_USING_MBUS'),
    ('sid/sid-sun252i.c', ''),
    ('audio/codec-sun252i.c', 'RT_USING_AUDIO'),
    ('audio/i2s-sun252i.c', 'RT_USING_AUDIO'),
    ('audio/owa-sun252i.c', 'RT_USING_AUDIO'),
    ('mipi_dbi/mipi-dbi-sun252i.c', 'BSP_USING_DBI'),
    ('usb/phy/usb-phy-sun252i.c', ''),
    ('usb/cherryusb/usb-otg-sun252i.c', ''),
    ('usb/cherryusb/usb-hci-sun252i.c', 'RT_CHERRYUSB_HOST'),
    ('usb/cherryusb/usb_hc_ohci.c', 'RT_CHERRYUSB_HOST'),
    ('interrupt_controller/trap_riscv.c', ''),
]

src = Glob('*.S')
for f, dep in drivers:
    if dep == '' or GetDepend(dep):
        src.append(f)

# every driver directory holds its own headers
CPPPATH = [cwd, os.path.join(cwd, 'include'), os.path.join(cwd, '..', 'dts', 'include'), os.path.join(cwd, 'mbus'), os.path.join(cwd, 'sid'), os.path.join(cwd, 'spif'), os.path.join(cwd, 'audio'), os.path.join(cwd, 'dma'),
           os.path.join(cwd, '..', '..', '..', '..', 'components', 'drivers', 'pin')]
for d in sorted({os.path.dirname(f) for f, _ in drivers}):
    CPPPATH.append(os.path.join(cwd, d))

# the CherryUSB component of the tree: the ports and classes the glue code includes
cherryusb = os.path.join(cwd, '..', '..', '..', '..', 'components', 'drivers', 'usb', 'cherryusb')
CPPPATH += [os.path.join(cherryusb, 'common'), os.path.join(cherryusb, 'core'), os.path.join(cherryusb, 'osal'),
            os.path.join(cherryusb, 'port', 'ehci'), os.path.join(cherryusb, 'port', 'ohci'),
            os.path.join(cherryusb, 'port', 'musb'), os.path.join(cherryusb, 'class', 'hub'),
            os.path.join(cherryusb, 'class', 'cdc'), os.path.join(cherryusb, 'class', 'msc'),
            os.path.join(cherryusb, 'class', 'vendor', 'display')]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, ASFLAGS = ' -I ' + cwd)

# drivers with a directory of their own
for d in ['display', 'g2d', 'vdec']:
    if d == 'g2d' and not GetDepend('BSP_USING_G2D'):
        continue
    group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
