/*
 * Copyright (c) 2006-2026, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * S/PDIF (OWA) transmitter and receiver, fed by cyclic DMA rings. The
 * receiver module clock selects the audio PLL outputs at sources 1 (/2) and
 * 2 (/5), the transmitter at 0 and 1.
 */
#include <rtthread.h>
#include <rtdevice.h>
#include <string.h>
#include "dma-sun252i.h"
#include "owa-sun252i.h"


#define OWA_CTL         0x00
#define OWA_TXCFG       0x04
#define OWA_RXCFG       0x08
#define OWA_INT_STA     0x0c
#define OWA_RXFIFO      0x10
#define OWA_FIFO_CTL    0x14
#define OWA_INT         0x1c
#define OWA_TXFIFO      0x20
#define OWA_TXCNT       0x24
#define OWA_RXCNT       0x28
#define OWA_TXCH_STA0   0x2c
#define OWA_TXCH_STA1   0x30
#define OWA_RXCH_STA0   0x34

#define BIT(n)          (1u << (n))
#define CTL_RESET       BIT(0)
#define CTL_GEN_EN      BIT(1)
#define CTL_LOOP_EN     BIT(2)
#define TXCFG_TXEN      BIT(0)
#define TXCFG_CHAN_STA_EN BIT(1)
#define TXCFG_SAMPLE_SHIFT 2
#define TXCFG_DIV_SHIFT 4
#define TXCFG_DIV_MASK  (0x1fu << TXCFG_DIV_SHIFT)
#define TXCFG_SINGLE_MOD BIT(31)
#define RXCFG_RXEN      BIT(0)
#define RXCFG_CHSR_CP   BIT(1)
#define FIFO_RXOM_MASK  0x3u
#define FIFO_TXIM       BIT(2)
#define FIFO_RXTL_SHIFT 4
#define FIFO_TXTL_SHIFT 12
#define FIFO_FRX        BIT(29)
#define FIFO_FTX        BIT(30)
#define INT_RXDRQEN     BIT(2)
#define INT_TXDRQEN     BIT(7)
#define CHSTA0_CHNUM_SHIFT 20
#define CHSTA0_FREQ_SHIFT 24
#define CHSTA1_WORDLEN_MASK 0xfu
#define CHSTA1_ORIFREQ_SHIFT 4

static struct
{
    rt_uint32_t period_bytes, periods;
    rt_uint8_t *tx, *rx;
    volatile rt_uint32_t tx_periods, rx_periods;
    rt_bool_t open, tx_clk, rx_clk;
    rt_ubase_t base;
    struct rt_clk *bus, *tx_mod, *rx_mod;
    struct rt_reset_control *rst;
    struct rt_dma_chan *tx_chan, *rx_chan;
} st;

static rt_uint32_t rd(rt_uint32_t o) { return HWREG32(st.base + o); }
static void wr(rt_uint32_t o, rt_uint32_t v) { HWREG32(st.base + o) = v; }
static void upd(rt_uint32_t o, rt_uint32_t m, rt_uint32_t v) { wr(o, (rd(o) & ~m) | (v & m)); }

static void tx_cb(struct rt_dma_chan *chan, rt_size_t size) { if (size) st.tx_periods++; }
static void rx_cb(struct rt_dma_chan *chan, rt_size_t size) { if (size) st.rx_periods++; }

/* 48 kHz, 16 bit stereo; the channel status carries the frequency codes */
int sun252i_owa_open(rt_uint32_t period_frames, rt_uint32_t periods, rt_bool_t loopback)
{
    rt_uint32_t base = 24576000u, div = base / (128u * 48000u);

    if (st.open || periods > 8u || div < 1u || div > 32u)
        return -1;
    rt_reset_control_assert(st.rst);
    rt_clk_prepare_enable(st.bus);
    rt_reset_control_deassert(st.rst);

    /* FIFO levels, channel status generated by the hardware, two channels in the status */
    upd(OWA_FIFO_CTL, (0xffu << FIFO_TXTL_SHIFT) | (0x7fu << FIFO_RXTL_SHIFT), (0x40u << FIFO_TXTL_SHIFT) | (0x20u << FIFO_RXTL_SHIFT));
    upd(OWA_TXCFG, TXCFG_CHAN_STA_EN, TXCFG_CHAN_STA_EN);
    wr(OWA_TXCH_STA0, 2u << CHSTA0_CHNUM_SHIFT);
    wr(OWA_RXCH_STA0, 2u << CHSTA0_CHNUM_SHIFT);
    upd(OWA_CTL, CTL_RESET | CTL_GEN_EN, CTL_RESET);

    if (rt_clk_set_rate(st.tx_mod, base) != RT_EOK)
        return -3;
    rt_clk_prepare_enable(st.tx_mod);
    st.tx_clk = RT_TRUE;
    if (rt_clk_set_rate(st.rx_mod, base) != RT_EOK)
        return -4;
    rt_clk_prepare_enable(st.rx_mod);
    st.rx_clk = RT_TRUE;

    upd(OWA_CTL, CTL_LOOP_EN, loopback ? CTL_LOOP_EN : 0u);
    /* transmitter: 16 bit samples, divider for 48 kHz, frequency codes of the channel status */
    upd(OWA_TXCFG, (3u << TXCFG_SAMPLE_SHIFT) | TXCFG_DIV_MASK | TXCFG_SINGLE_MOD, ((div - 1u) << TXCFG_DIV_SHIFT));
    upd(OWA_FIFO_CTL, FIFO_TXIM, FIFO_TXIM);
    upd(OWA_TXCH_STA0, 0xfu << CHSTA0_FREQ_SHIFT, 0x2u << CHSTA0_FREQ_SHIFT);
    upd(OWA_TXCH_STA1, (0xfu << CHSTA1_ORIFREQ_SHIFT) | CHSTA1_WORDLEN_MASK, (0xdu << CHSTA1_ORIFREQ_SHIFT) | 0x2u);
    upd(OWA_FIFO_CTL, FIFO_RXOM_MASK, 3u);
    upd(OWA_RXCH_STA0, 0xfu << CHSTA0_FREQ_SHIFT, 0x2u << CHSTA0_FREQ_SHIFT);

    st.period_bytes = period_frames * 4u;
    st.periods = periods;
    st.tx = rt_malloc_align(st.period_bytes * periods, 64);
    st.rx = rt_malloc_align(st.period_bytes * periods, 64);
    if (!st.tx || !st.rx)
        return -5;
    memset(st.rx, 0, st.period_bytes * periods);
    st.open = RT_TRUE;
    return 0;
}

rt_uint8_t *sun252i_owa_tx_buffer(void) { return st.tx; }
rt_uint8_t *sun252i_owa_rx_buffer(void) { return st.rx; }
rt_uint32_t sun252i_owa_tx_periods(void) { return st.tx_periods; }
rt_uint32_t sun252i_owa_rx_periods(void) { return st.rx_periods; }

rt_uint32_t sun252i_owa_reg(rt_uint32_t off) { return rd(off); }

static rt_err_t ring_prepare(struct rt_dma_chan *chan, enum rt_dma_transfer_direction dir, rt_ubase_t fifo,
                             rt_uint8_t *buf, void (*cb)(struct rt_dma_chan *, rt_size_t))
{
    struct rt_dma_slave_config conf = { .direction = dir };
    struct rt_dma_slave_transfer t = { 0 };
    rt_err_t err;

    conf.src_addr_width = conf.dst_addr_width = RT_DMA_SLAVE_BUSWIDTH_2_BYTES;
    conf.src_maxburst = conf.dst_maxburst = 8;
    if (dir == RT_DMA_MEM_TO_DEV)
    {
        conf.dst_addr = fifo;
        t.src_addr = (rt_ubase_t)buf;
    }
    else
    {
        conf.src_addr = fifo;
        t.dst_addr = (rt_ubase_t)buf;
    }
    t.buffer_len = st.period_bytes * st.periods;
    t.period_len = st.period_bytes;
    chan->callback = cb;
    if ((err = rt_dma_chan_config(chan, &conf)))
        return err;
    if ((err = rt_dma_prep_cyclic(chan, &t)))
        return err;

    return rt_dma_chan_start(chan);
}

int sun252i_owa_start(void)
{
    if (!st.open)
        return -1;
    rt_hw_cpu_dcache_ops(RT_HW_CACHE_FLUSH, st.tx, st.period_bytes * st.periods);
    st.tx_periods = st.rx_periods = 0;
    upd(OWA_CTL, CTL_GEN_EN, CTL_GEN_EN);
    wr(OWA_INT_STA, rd(OWA_INT_STA));

    if (ring_prepare(st.rx_chan, RT_DMA_DEV_TO_MEM, st.base + OWA_RXFIFO, st.rx, rx_cb))
        return -2;
    upd(OWA_FIFO_CTL, FIFO_FRX, FIFO_FRX);
    wr(OWA_RXCNT, 0);
    upd(OWA_RXCFG, RXCFG_CHSR_CP, RXCFG_CHSR_CP);
    upd(OWA_INT, INT_RXDRQEN, INT_RXDRQEN);
    upd(OWA_RXCFG, RXCFG_RXEN, RXCFG_RXEN);

    if (ring_prepare(st.tx_chan, RT_DMA_MEM_TO_DEV, st.base + OWA_TXFIFO, st.tx, tx_cb))
        return -3;
    upd(OWA_FIFO_CTL, FIFO_FTX, FIFO_FTX);
    wr(OWA_TXCNT, 0);
    upd(OWA_TXCFG, TXCFG_TXEN, TXCFG_TXEN);
    upd(OWA_INT, INT_TXDRQEN, INT_TXDRQEN);
    return 0;
}

void sun252i_owa_stop(void)
{
    upd(OWA_TXCFG, TXCFG_TXEN, 0);
    upd(OWA_RXCFG, RXCFG_RXEN, 0);
    upd(OWA_INT, INT_TXDRQEN | INT_RXDRQEN, 0);
    rt_dma_chan_stop(st.tx_chan);
    rt_dma_chan_stop(st.rx_chan);
}

void sun252i_owa_close(void)
{
    if (!st.open)
        return;
    sun252i_owa_stop();
    if (st.tx_clk) { rt_clk_disable_unprepare(st.tx_mod); st.tx_clk = RT_FALSE; }
    if (st.rx_clk) { rt_clk_disable_unprepare(st.rx_mod); st.rx_clk = RT_FALSE; }
    rt_free_align(st.tx);
    rt_free_align(st.rx);
    st.tx = st.rx = RT_NULL;
    st.open = RT_FALSE;
}

static rt_err_t owa_probe(struct rt_platform_device *pdev)
{
    struct rt_device *dev = &pdev->parent;

    st.base = (rt_ubase_t)rt_dm_dev_iomap(dev, 0);
    st.bus = rt_clk_get_by_name(dev, "bus");
    st.tx_mod = rt_clk_get_by_name(dev, "tx");
    st.rx_mod = rt_clk_get_by_name(dev, "rx");
    st.rst = rt_reset_control_get_by_index(dev, 0);
    st.tx_chan = rt_dma_chan_request(dev, "tx");
    st.rx_chan = rt_dma_chan_request(dev, "rx");
    if (!st.base || rt_is_err_or_null(st.bus) || rt_is_err_or_null(st.tx_mod) || rt_is_err_or_null(st.rx_mod) ||
        rt_is_err_or_null(st.rst) || rt_is_err_or_null(st.tx_chan) || rt_is_err_or_null(st.rx_chan))
    {
        return -RT_ERROR;
    }

    return RT_EOK;
}

static const struct rt_ofw_node_id owa_ofw_ids[] =
{
    { .compatible = "allwinner,sun252i-owa" },
    { /* sentinel */ }
};

static struct rt_platform_driver owa_driver =
{
    .name = "owa-sun252i",
    .ids = owa_ofw_ids,
    .probe = owa_probe,
};
RT_PLATFORM_DRIVER_EXPORT(owa_driver);
