from building import *

group = []

if not GetDepend(['RT_USING_DMA']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['dma.c']

# the coherent pools map pages through the MMU
if GetDepend(['ARCH_MM_MMU']):
    src += ['dma_pool.c']

if GetDepend(['RT_DMA_PL330']):
    src += ['dma-pl330.c']

if GetDepend(['RT_DMA_DW_AXI_DMAC']):
    src += ['dma-dw-axi-dmac.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
