/* RT-Thread config file of the Allwinner sun252iw2 BSP */
#ifndef __RTCONFIG_H__
#define __RTCONFIG_H__

/* BSP_PROFILE_USBDISP (SUN252I_BOARD=usbdisp) leaves out everything the USB second screen does not use */
#include "profile.h"

/* RT-Thread Kernel */
#define RT_NAME_MAX 16
#define RT_ALIGN_SIZE 4
#define RT_THREAD_PRIORITY_32
#define RT_THREAD_PRIORITY_MAX 32
#define RT_TICK_PER_SECOND 100
#define RT_USING_OVERFLOW_CHECK
#define RT_USING_HOOK
#define RT_USING_IDLE_HOOK
#define RT_IDEL_HOOK_LIST_SIZE 4
#define IDLE_THREAD_STACK_SIZE 4096
#define RT_USING_TIMER_SOFT
#define RT_TIMER_THREAD_PRIO 4
#define RT_TIMER_THREAD_STACK_SIZE 2048

/* Debug */
#define RT_DEBUG
#define RT_DEBUG_COLOR

/* Inter-Thread communication */
#define RT_USING_SEMAPHORE
#define RT_USING_MUTEX
#define RT_USING_EVENT
#define RT_USING_MAILBOX
#define RT_USING_MESSAGEQUEUE

/* Memory Management */
#define RT_USING_MEMPOOL
#define RT_USING_SMALL_MEM
#define RT_USING_SMALL_MEM_AS_HEAP
#define RT_USING_HEAP

/* Kernel Device Object */
#define RT_USING_DEVICE
#define RT_USING_CONSOLE
#define RT_USING_USER_MAIN
#define RT_MAIN_THREAD_STACK_SIZE 8192
#define RT_MAIN_THREAD_PRIORITY 10
#define RT_CONSOLEBUF_SIZE 256
#define RT_CONSOLE_DEVICE_NAME "uart3"

/* RT-Thread Components */
#define RT_USING_COMPONENTS_INIT
#define RT_USING_FINSH
#define FINSH_USING_MSH
#define FINSH_USING_MSH_DEFAULT
#define FINSH_USING_SYMTAB
#define FINSH_SYMBOL_PREFIX
#define FINSH_THREAD_STACK_SIZE 4096
#define MSH_USING_BUILT_IN_COMMANDS
#define FINSH_USING_DESCRIPTION
#define FINSH_USING_HISTORY
#define FINSH_HISTORY_LINES 5
#define MSH_CMD_EXPORT_ALL

/* Device Drivers */
#define RT_USING_DEVICE_IPC
#define RT_USING_HW_ATOMIC

/* device model with a builtin device tree */
#define RT_USING_DM

/* the tests (applications/tests: test_*, test_all) and the speed measurements (applications/bench: *_bench) */
/* #define BSP_USING_TESTS */
/* #define BSP_USING_BENCH */
#define RT_USING_CLOCK_TIME
#define RT_USING_ADT
#define RT_USING_ADT_REF
#define RT_USING_ADT_BITMAP
#define RT_USING_OFW
#define RT_USING_BUILTIN_FDT
#define RT_FDT_EARLYCON_MSG_SIZE 128
#define RT_USING_OFW_BUS_RANGES_NUMBER 4
#define RT_USING_PIC
#define MAX_HANDLERS 256
#define RT_USING_CLK
#define RT_USING_RESET
#define RT_USING_PINCTRL
#define RT_USING_CACHE
#define RT_USING_DMA
#define RT_UNAUTHENTICATED_DEVICE_IPC
#define RT_USING_SERIAL
#define RT_USING_SERIAL_V1
#define RT_SERIAL_8250
#define RT_SERIAL_8250_DW
#define RT_SERIAL_RB_BUFSZ 128
#define RT_USING_PIN

#define RT_USING_I2C
#ifndef BSP_PROFILE_USBDISP
#define RT_USING_SPI
#define RT_USING_MTD_NOR
#endif
#define RT_USING_PWM
#define RT_USING_CHERRYUSB
#define RT_CHERRYUSB_DEVICE
#define RT_CHERRYUSB_DEVICE_MUSB_SUNXI
#define RT_CHERRYUSB_DEVICE_SPEED_HS
#ifndef BSP_PROFILE_USBDISP
#define RT_CHERRYUSB_DEVICE_CDC_ACM
#endif
#define RT_CHERRYUSB_DEVICE_DISPLAY
#define RT_CHERRYUSB_DEVICE_HID
#ifndef BSP_PROFILE_USBDISP
#define RT_CHERRYUSB_HOST
#define RT_CHERRYUSB_HOST_EHCI_CUSTOM
#define RT_CHERRYUSB_HOST_MSC
#define RT_CHERRYUSB_HOST_CDC_ACM
#endif
#ifndef BSP_PROFILE_USBDISP
#define RT_USING_AUDIO
#define RT_AUDIO_REPLAY_MP_BLOCK_SIZE 4096
#define RT_AUDIO_REPLAY_MP_BLOCK_COUNT 4
#define RT_AUDIO_RECORD_PIPE_SIZE 2048
#define RT_USING_SDIO
#define RT_SDIO_STACK_SIZE 4096
#define RT_SDIO_THREAD_PRIORITY 15
#define RT_MMCSD_STACK_SIZE 4096
#define RT_MMCSD_THREAD_PRIORITY 22
#define RT_MMCSD_MAX_PARTITION 16
#define RT_USING_BLK

/* DFS with FAT on the SD card */
#define RT_USING_DFS
#define DFS_USING_POSIX
#define DFS_USING_WORKDIR
#define DFS_FD_MAX 16
#define RT_USING_DFS_V1
#define RT_USING_DFS_ELMFAT
#define RT_DFS_ELM_CODE_PAGE 437
#define RT_DFS_ELM_WORD_ACCESS
#define RT_DFS_ELM_USE_LFN_3
#define RT_DFS_ELM_USE_LFN 3
#define RT_DFS_ELM_LFN_UNICODE_0
#define RT_DFS_ELM_LFN_UNICODE 0
#define RT_DFS_ELM_MAX_LFN 255
#define RT_DFS_ELM_DRIVES 2
#define RT_DFS_ELM_MAX_SECTOR_SIZE 512
#define RT_DFS_ELM_REENTRANT
#define RT_DFS_ELM_MUTEX_TIMEOUT 3000
#define RT_USING_DFS_DEVFS
#define RT_USING_ADC
#define RT_USING_WDT
#define BSP_USING_MP4
#define BSP_USING_G2D
#define BSP_USING_MBUS
#define BSP_USING_DBI
#endif

/* sun252iw2 SoC */
#define ARCH_RISCV
#define ARCH_RISCV_FPU
#define ARCH_RISCV_FPU_D
#define RT_HW_ISR_NUM 192
#define RT_HW_HEAP_BEGIN 0x40200000
#define RT_HW_HEAP_END   0x40E00000
#define RT_HW_STACK_GUARD
#define RT_CPUS_NR 1
#define RT_BACKTRACE_LEVEL_MAX_NR 32


#endif
